In [3]:
import tensorflow as tf
from tensorflow import keras
tf.__version__

'2.2.0'

In [2]:
tf.executing_eagerly()


True

In [5]:
x=[[2,]]
m=tf.matmul(x,x)
print(m)
m.numpy()

tf.Tensor([[4]], shape=(1, 1), dtype=int32)


array([[4]])

In [7]:
a = tf.constant([[1,2],[3,4]])
a
a.numpy()

array([[1, 2],
       [3, 4]])

In [8]:
b=tf.add(a,1)
b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]])>

In [14]:
import numpy as np
d=np.array([[5,6],[7,8]])
a+d


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  8],
       [10, 12]])>

In [15]:
(a+d).numpy()

array([[ 6,  8],
       [10, 12]])

In [16]:
g=tf.convert_to_tensor(10)
float(g)

10.0

In [9]:
c=tf.multiply(a,b)
c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2,  6],
       [12, 20]])>

In [10]:
num = tf.convert_to_tensor(10)
num

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [11]:
for i in range(num.numpy()):
    i = tf.constant(i)
    if int(i%2)==0:
        print('even')
    else:
        print('odd')



even
odd
even
odd
even
odd
even
odd
even
odd
